export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_LIST_SHOW_TIME = "GET_LIST_SHOW_TIME";
export const GET_LIST_THEATER = "GET_LIST_THEATER";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_USER = "GET_LIST_USER";
export const POST_DETAIL_USER = "POST_DETAIL_USER";
export const GET_LIST_CHAIR_BOOKING = "GET_LIST_CHAIR_BOOKING"
